/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package googleTranslate.screenPlay.serenity;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
